packages:
  - 'demo'
  - 'infra/*'
  - 'packages/*'

catalog:
  '@types/markdown-it': ^13.0.0
  '@types/node': ^24.10.4
  react-use: ^17.3.2

catalogs:
  peers:
    'highlight.js': ^11.8.0
    katex: ^0.16.9
    lowlight: 3.0.0
    markdown-it: ^13.0.0

  peer-diplodoc:
    '@diplodoc/cut-extension': ^1.1.0
    '@diplodoc/file-extension': ^0.2.1
    '@diplodoc/folding-headings-extension': ^0.1.2
    '@diplodoc/html-extension': ^2.9.1
    '@diplodoc/latex-extension': ^1.4.1
    '@diplodoc/mermaid-extension': ^1.4.0
    '@diplodoc/quote-link-extension': 0.1.3
    '@diplodoc/tabs-extension': ^3.7.5
    '@diplodoc/transform': 4.66.0

  peer-gravity:
    '@gravity-ui/components': 4.10.0
    '@gravity-ui/uikit': ^7.13.1

  ts:
    '@gravity-ui/tsconfig': 1.0.0
    tslib: ^2.3.1
    typescript: ^5.9.3

  linters:
    eslint: 9.39.2
    postcss: 8.5.6
    prettier: 3.7.4
    stylelint: 16.26.1

  react:
    '@types/react': 18.0.28
    '@types/react-dom': 18.0.11
    react: 18.2.0
    react-dom: 18.2.0
  react16:
    react: ^16.14.0
    react-dom: ^16.14.0
  react17:
    react: ^17.0.0
    react-dom: ^17.0.0
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
