import {
    Bell,
    Book,
    Briefcase,
    BucketPaint,
    Calendar,
    Camera,
    ChartColumn,
    CircleInfo,
    Clock,
    Cloud,
    Code,
    Comment,
    Comments,
    CreditCard,
    Cubes3,
    Envelope,
    File,
    Flag,
    Folder,
    Gear,
    Gift,
    Globe,
    GraduationCap,
    Headphones,
    Heart,
    House,
    Key,
    LayoutCells,
    Lock,
    Magnifier,
    Megaphone,
    Person,
    PersonPlus,
    Picture,
    Rocket,
    ShieldCheck,
    Star,
    Tag,
    Target,
    ThumbsUp,
    Thunderbolt,
    Wrench,
} from '@gravity-ui/icons';
import type {IconData} from '@gravity-ui/uikit';

export interface ConstructorIcon {
    id: string;
    data: IconData;
}

// A curated subset of @gravity-ui/icons offered when replacing an inline SVG.
// The `id` doubles as a stable key and a fallback tooltip label.
export const HTML_CONSTRUCTOR_ICONS: ConstructorIcon[] = [
    {id: 'comment', data: Comment},
    {id: 'comments', data: Comments},
    {id: 'shield-check', data: ShieldCheck},
    {id: 'thunderbolt', data: Thunderbolt},
    {id: 'chart-column', data: ChartColumn},
    {id: 'book', data: Book},
    {id: 'globe', data: Globe},
    {id: 'lock', data: Lock},
    {id: 'key', data: Key},
    {id: 'cubes', data: Cubes3},
    {id: 'file', data: File},
    {id: 'folder', data: Folder},
    {id: 'person', data: Person},
    {id: 'person-plus', data: PersonPlus},
    {id: 'headphones', data: Headphones},
    {id: 'layout-cells', data: LayoutCells},
    {id: 'star', data: Star},
    {id: 'heart', data: Heart},
    {id: 'thumbs-up', data: ThumbsUp},
    {id: 'bell', data: Bell},
    {id: 'gear', data: Gear},
    {id: 'house', data: House},
    {id: 'magnifier', data: Magnifier},
    {id: 'calendar', data: Calendar},
    {id: 'clock', data: Clock},
    {id: 'envelope', data: Envelope},
    {id: 'cloud', data: Cloud},
    {id: 'rocket', data: Rocket},
    {id: 'flag', data: Flag},
    {id: 'tag', data: Tag},
    {id: 'target', data: Target},
    {id: 'gift', data: Gift},
    {id: 'graduation-cap', data: GraduationCap},
    {id: 'megaphone', data: Megaphone},
    {id: 'briefcase', data: Briefcase},
    {id: 'credit-card', data: CreditCard},
    {id: 'circle-info', data: CircleInfo},
    {id: 'wrench', data: Wrench},
    {id: 'code', data: Code},
    {id: 'picture', data: Picture},
    {id: 'camera', data: Camera},
    {id: 'palette', data: BucketPaint},
];
