const image = 'https://storage.yandexcloud.net/gravity-ui/markdown-editor/header-cover.png';

export const markup = {
    empty: `::header[]{fill="blue"}\n`,

    formats: [
        '::header[Портал команды Вики]{fill="blue"}',
        '',
        '::header[Дежурства]{format="small" bg="fill" fill="navy"}',
        '',
    ].join('\n'),

    /** Сценарии фона из каталога: слой фона отдельно, изображение со слоем поверх отдельно. */
    backgrounds: [
        '# Слой фона',
        '',
        '::header[Сплошная заливка]{bg="fill" fill="yellow"}',
        '',
        '::header[Заливка с фигурами]{fill="blue"}',
        '',
        '::header[Градиент]{bg="gradient" fill="indigo" fill2="violet"}',
        '',
        '::header[Меш-градиент]{bg="mesh" fill="violet" fill2="sky"}',
        '',
        '::header[Паттерн]{bg="pattern" fill="sky"}',
        '',
        '# Изображение и слой поверх него',
        '',
        `::header[Фотография]{fill="blue" image="${image}" text="dark"}`,
        '',
        `::header[Размытие]{fill="blue" effect="blur" image="${image}"}`,
        '',
        `::header[Затемнение]{fill="blue" effect="dim" image="${image}"}`,
        '',
        `::header[Цвет слева, фото справа]{fill="sand" effect="gradient" image="${image}"}`,
        '',
    ].join('\n'),

    fills: [
        '::header[Синий]{bg="fill" fill="blue"}',
        '',
        '::header[Индиго]{bg="fill" fill="indigo"}',
        '',
        '::header[Фиолетовый]{bg="fill" fill="purple"}',
        '',
        '::header[Сиреневый]{bg="fill" fill="violet"}',
        '',
        '::header[Бирюзовый]{bg="fill" fill="teal"}',
        '',
        '::header[Зелёный]{bg="fill" fill="green"}',
        '',
        '::header[Небесный]{bg="fill" fill="sky"}',
        '',
        '::header[Янтарный]{bg="fill" fill="amber"}',
        '',
        '::header[Жёлтый]{bg="fill" fill="yellow"}',
        '',
        '::header[Песочный]{bg="fill" fill="sand"}',
        '',
        '::header[Красный]{bg="fill" fill="red"}',
        '',
        '::header[Тёмно-синий]{bg="fill" fill="navy"}',
        '',
    ].join('\n'),

    seeds: [
        '::header[Раскладка из макета]{fill="purple" seed="0"}',
        '',
        '::header[Другая раскладка]{fill="purple" seed="481203"}',
        '',
        '::header[И ещё одна]{bg="mesh" fill="indigo" fill2="red" seed="77"}',
        '',
    ].join('\n'),

    insideCut: [
        '{% cut "Обложка внутри ката" %}',
        '',
        '::header[Портал команды Вики]{fill="green"}',
        '',
        '{% endcut %}',
        '',
    ].join('\n'),

    unknownValues: `::header[Неизвестные значения]{format="huge" bg="rainbow" fill="magenta"}\n`,
};
