name: PR Preview Build

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install Packages
        run: npm ci
        shell: bash
      - name: Build Storybook
        run: npm run storybook:build
        shell: bash
      - name: Create Static Artifact
        uses: actions/upload-artifact@v2
        with:
          name: static
          path: ./storybook-static
      - name: Save PR ID
        run: |
          pr="${{ github.event.pull_request.number }}"
          echo $pr > ./pr-id.txt
        shell: bash
      - name: Create PR Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: ./pr-id.txt
